# Generated by Django 6.0.4 on 2026-05-22 00:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0006_screening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='seats count')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekująca'), ('CONFIRMED', 'Potwierdzona'), ('CANCELLED', 'Anulowana')], default='PENDING', max_length=12, verbose_name='status')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe payment intent ID')),
                ('refund_id', models.CharField(blank=True, default='', max_length=255, verbose_name='refund ID')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='refunded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.screening', verbose_name='screening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='booking_status_expires_idx')],
            },
        ),
    ]
