# Generated by Django 6.0.4 on 2026-05-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, upload_to='actors', verbose_name='photo')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'ordering': ('full_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
    ]
