# Generated by Django 6.0.4 on 2026-05-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_alter_genre_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, upload_to='directors/', verbose_name='photo')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'ordering': ('full_name',),
            },
        ),
    ]
