# Generated by Django 6.0.4 on 2026-05-20 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_hall_alter_actor_full_name_alter_actor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration (minutes)')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='poster')),
                ('trailer_url', models.URLField(blank=True, verbose_name='trailer URL')),
                ('actors', models.ManyToManyField(related_name='movies', to='cinema.actor', verbose_name='actors')),
                ('directors', models.ManyToManyField(related_name='movies', to='cinema.director', verbose_name='directors')),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ('-release_date', 'title'),
            },
        ),
    ]
