# Generated by Django 6.0.4 on 2026-05-20 01:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.hall', verbose_name='hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'screening',
                'verbose_name_plural': 'screenings',
                'ordering': ('start_time',),
            },
        ),
    ]
